#服务名
spring:
  application:
    name: lowcode-core
  #邮箱配置
  mail:
    #示例：smtp.qq.com
    host: 
    #示例：marsview@qq.com
    username:
    #示例：nqmblqofepasgjhd，qq邮箱获取https://service.mail.qq.com/detail/0/75
    password:
    properties: { 'mail.smtp.ssl.enable', true }
    #如果启动就检查邮箱配置是否连接正常配置为true
    test-connection: false
    protocol: smtps
    port: 465
  #redis配置
  data:
    redis:
      host:
      port:
      password:
      database:

#服务端口
server:
  port: 9001

#mybatis配置
mybatis:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  # mybatis对应的实体类
  mapper-locations: classpath:com/**/mapper/**/*.xml
  type-aliases-package: com.**.domain

#打印sql日志
logging:
  config: classpath:logback.xml
